/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#444748",
        "text-primary": "#1A1A1A",
        "text-muted": "#888888",
        "background-primary": "#F5F5F7",
        "background-sidebar": "#FFFFFF",
        "background": "#fdf8f8",
        "surface": "#fdf8f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f2",
        "surface-container": "#f1edec",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e5e2e1",
        "secondary-container": "#dfdfe1",
        "on-secondary-container": "#616365",
        "border-subtle": "#E8E8E8",
        "sidebar-active": "#F0F0F0",
        "accent-source-highlight": "#FDE68A",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c7c7",
        "dark-bg": "#111111",
        "dark-sidebar": "#1A1A1A",
        "dark-text": "#F0F0F0",
        "dark-border": "#2A2A2A",
        "dark-card": "#1F1F1F",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "240px",
        "container-padding": "32px",
      },
      fontFamily: {
        "card-title": ["Manrope", "sans-serif"],
        "breadcrumb": ["Inter", "sans-serif"],
        "body-main": ["Manrope", "sans-serif"],
        "section-heading": ["Manrope", "sans-serif"],
        "hero-headline": ["Manrope", "sans-serif"],
        "source-chip": ["Inter", "sans-serif"],
      },
      fontSize: {
        "card-title": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
        "breadcrumb": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-main": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "section-heading": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "hero-headline": ["56px", { lineHeight: "1.05", fontWeight: "800" }],
        "source-chip": ["11px", { lineHeight: "1", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
